chat/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('chat.views',
                       url(r'^$', "chat", name='chat'),
                       url(r'^archive$', views.MessageList.as_view(), name='archive'),
                       )

pm/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('pm.views',
                       url(r'^$', views.MessageList.as_view(), name='inbox'),
                       url(r'^/outbox$', views.MessageList.as_view(),
                           {'filter': 'outbox'}, name='outbox',
                           ),
                       url(r'^/all$', views.MessageList.as_view(),
                           {'filter': 'all'}, name='all', ),

                       url(r'^/new$', views.MessageCreate.as_view(), name='new', ),

                       url(r'^/new/(?P<username>\w+)$', views.MessageCreate.as_view(), name='new_to', ),

                       url(r'^/delete', 'delete_messages', name='delete',
                           ),
                       )

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^', include('core.urls', namespace='core')),
                       url(r'^', include('authn.urls', namespace='authn')),
                       url(r'^users/', include('users.urls', namespace='users')),
                       url(r'^pass/', include('password.urls', namespace='password')),
                       url(r'^reg/', include('registration.urls', namespace='registration')),

                       url(r'^', include('chat.urls', namespace='chat')),

                       url(r'^pm', include('pm.urls', namespace='pm')),
                       )

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}))

registration/urls.py
# coding=utf-8
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from registration.forms import RegistrationForm
from registration.views import (RegistrationFormView,
                                RegistrationCompleteView,
                                RegistrationConfirmView)


urlpatterns = patterns(
    '',

    url(r'^basic$',
        RegistrationFormView.as_view(form_class=RegistrationForm),
        name='basic'),

    url(r'^welcome$',
        RegistrationCompleteView.as_view(),
        name='complete'),

    url(r'^confirm/(?P<pk>\d+)/(?P<code>\w+)$',
        RegistrationConfirmView.as_view(),
        name='confirm'),
)

chat/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings

from sanitizer.models import SanitizedTextField

User = settings.AUTH_USER_MODEL


class Message(models.Model):
    user = models.ForeignKey(User, related_name="messages")
    text = SanitizedTextField(allowed_tags=['a', 'img', 'i', 'b'],
                              allowed_attributes=['href', 'src'],
                              strip=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'.encode('utf-8')
        # ordering = ['created']

    def __unicode__(self):
        return self.text[:100]

chat/views.py
# coding=utf-8
from __future__ import unicode_literals

from django.contrib.auth import authenticate, login, get_user_model
from django.conf import settings
from django.shortcuts import render
from django.views import generic

User = get_user_model()

from .models import Message


def chat(request):
    if not request.user.is_authenticated():

        try:
            user = User.objects.create_user(
                is_temp=True
            )
            user.set_unusable_password()
            user.save()

            authenticate(user=user)
            login(request, user)
        except:
            pass

    return render(request, 'chat/chat.html', {
        'socket_port': settings.SOCKJS_PORT,
        'socket_channel': settings.SOCKJS_CHANNEL
    })


class MessageList(generic.ListView):
    model = Message
    paginate_by = 20

    def get_queryset(self):

        text = self.request.GET.get('q', None)

        if text:
            object_list = self.model.objects.filter(text__icontains=text)
        else:
            object_list = self.model.objects.all()
        return object_list

chat/templates/chat/chat.html
{% extends 'base.html' %}
{% load staticfiles thumbnail %}

{% block title %}Не дает .(с)ру - чат троллей, девественников и лжецов,
    а также профессиольных онананистов-приколистов{% endblock %}

{% block content %}

    <div class="header">
        <h1 class="header_t"><span class="logo">Не дает .(с)ру </span>
            <span style="margin-right: 16px;">–</span>чат троллей, девественников и лжецов,
            а также профессиольных онананистов-приколистов</h1>

        <div class="header_second">
            {% if request.user.is_authenticated and not request.user.is_temp %}

                <a href="{% url 'pm:inbox' %}"
                   class="header_second_i __notices">
                    <i class="mic-mail"></i>
                        <span class="__notices_count __hide" id="notifyCount"
                                >0</span>
                        <span class="__notices_l">
                            Личные сообщения
                        </span>
                </a>
                <a href="{% url 'users:update' request.user.username %}"
                   class="header_second_i __user">
                    <img
                            {% if request.user.avatar %}
                                {% thumbnail request.user.avatar "100x100" crop="center" format="PNG" as im %}
                                    src="{{ im.url }}"
                                {% endthumbnail %}
                            {% else %}
                                    src="{% static 'img/default/no_avatar.png' %}"
                            {% endif %}
                                    class="__user_ava"
                                    height="30" width="30" alt=""/>

                        <span class="__user_l">
                        Мой профайл
                        </span>
                </a>
                <a href="{% url 'authn:logout' %}" class="header_second_i">Выйти</a>
                <a href="{% url 'chat:archive' %}" class="header_second_i __archive">Архив сообщений</a>

            {% else %}

                <div class="header_second_auth">
                    <a class="header_second_auth_a" href="{% url 'authn:login' %}">Войти</a>
                    <a class="header_second_auth_a" href="{% url 'registration:basic' %}">Регистрация</a>
                </div>
            {% endif %}
        </div>
    </div>

    <div class="sidebar">
        <div class="sidebar_head">Сейчас в чате:</div>
        <div class="sidebar_contacts" id="contactList"></div>
    </div>

    <div class="help_place">
        <p class="help_place_t">
            Прыщавые двественники, омеги, пиздолисы, тролли, хикко-задроты и прочие дегенераты, которым
            больше нехуй делать в свободное время. Это клуб для вас.
            Зайди и проеби еще пару часов свой вонючей жизни.
        </p>
    </div>
    {% if request.user.is_authenticated %}
        <div class="chat" id="chat">

            <div class="chat_messages" id="msgList"></div>

            <div class="chat_form">
                <div class="chat_form_cnt">
                <textarea class="chat_form_cnt_it" id="msgInput"
                          onkeydown="app.chat.c.msgInputKeyDown(event)"
                          type="text" placeholder="Введите сообщение"></textarea>
                    <button class="chat_form_cnt_smile-btn btn"
                            onclick="app.chat.c.msgBtnSendClick(event)"
                            id="msgSendBtn"
                            title="Перенос строки: ctrl + enter. Для разметки используйте Markdown синтаксис. Например: **Привет**, будет жирным">
                        <i class="mic-send"></i></button>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block js_footer %}


{% endblock %}

chat/templates/chat/message_list.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}Архив сообщений |{% endblock %}

{% block content %}

    <!-- Begin p-navbar -->
    <div class="p-navbar">
        <a class="p-navbar_back" href="{% url "chat:chat" %}">
            <i class="mic-arrow-back"></i>
        </a>
        <ul class="p-navbar_t">
            <li class="p-navbar_t_i">
                <h4>Архив сообщений</h4>
            </li>
        </ul>

    </div>
    <!-- End p-navbar -->

    <div class="archive cnt __bg __padding">
        <div class="archive_search">

            <div class="minput">
                <input type="text" placeholder="Что ищем?"
                       class="archive_search_it"
                       id="searchIT"
                        />

                <span class="minput_highlight"></span>
                <span class="minput_bar"></span>
                <label>
                    Поиск

                    {% if field.help_text %}
                        (ищем по тексту)
                    {% endif %}
                </label>
            </div>

            <button class="archive_search_btn btn __raised __colored"
                    onclick="nav.go('archive?q=' + ge('searchIT').value, false, true);"
                    >Найти
            </button>
        </div>
        <div class="archive_messages">
            {% for message in object_list %}
                <div class="archive_messages_i">
                    <div class="archive_messages_i_date">
                        {{ message.created }}
                    </div>
                    <div class="archive_messages_i_name">
                        {{ message.user.username }}
                    </div>
                    <div class="archive_messages_i_txt">
                        {{ message.text }}
                    </div>
                </div>
            {% endfor %}
        </div>
        {% include 'core/paginator.html' %}
    </div>

{% endblock %}

{% block vanilla %}
    <script type="text/javascript">
        var q = getQueryVar("q");
        if (q) {
            ge('searchIT').value = q;
        }
    </script>
{% endblock %}

{% block js_footer %}
{% endblock %}