pm/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('pm.views',
                       url(r'^$', views.MessageList.as_view(), name='inbox'),
                       url(r'^/outbox$', views.MessageList.as_view(),
                           {'filter': 'outbox'}, name='outbox',
                           ),
                       url(r'^/all$', views.MessageList.as_view(),
                           {'filter': 'all'}, name='all', ),

                       url(r'^/new$', views.MessageCreate.as_view(), name='new', ),

                       url(r'^/new/(?P<username>\w+)$', views.MessageCreate.as_view(), name='new_to', ),

                       url(r'^/delete', 'delete_messages', name='delete',
                           ),
                       )

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^', include('core.urls', namespace='core')),
                       url(r'^', include('authn.urls', namespace='authn')),
                       url(r'^users/', include('users.urls', namespace='users')),
                       url(r'^pass/', include('password.urls', namespace='password')),
                       url(r'^reg/', include('registration.urls', namespace='registration')),

                       url(r'^', include('chat.urls', namespace='chat')),

                       url(r'^pm', include('pm.urls', namespace='pm')),
                       )

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}))

pm/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings

from sanitizer.models import SanitizedTextField, SanitizedCharField

User = settings.AUTH_USER_MODEL


class Message(models.Model):
    sender = models.ForeignKey('users.User', verbose_name='отправитель',
                               related_name="pm_sender_messages",
                               null=True)
    recipient = models.ForeignKey('users.User', verbose_name='получатель',
                                  related_name="pm_recipient_messages",
                                  null=True)

    subject = SanitizedCharField(verbose_name='тема', strip=False,
                                 max_length=100, null=True)

    text = SanitizedTextField(verbose_name='текст',
                              allowed_tags=['a', 'img'],
                              allowed_attributes=['href', 'src', 'width'],
                              strip=False)

    is_read = models.BooleanField('прочтено?', default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'личные сообщения'.encode('utf-8')
        ordering = ['created']

    def __unicode__(self):
        return self.text[:100]

pm/forms.py
# coding=utf-8
from __future__ import unicode_literals

from django import forms
from django.contrib.auth import get_user_model

from core.utils import get_object_or_none

User = get_user_model()

from .models import Message


class MessageForm(forms.ModelForm):
    recipient = forms.CharField(label='Ник получателя')
    subject = forms.CharField(label='Тема')
    text = forms.CharField(label='Текст сообщения', widget=forms.Textarea())

    class Meta:
        model = Message
        fields = ('recipient', 'subject', 'text')

    def clean_recipient(self):
        cleaned_data = self.cleaned_data
        recipient = cleaned_data.get('recipient')
        user = get_object_or_none(User, username=recipient)
        if not user:
            raise forms.ValidationError('Пользователя с таким ником не существует.')

        return user

pm/views.py
# coding=utf-8
from __future__ import unicode_literals

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views import generic
from django.db.models import Q
from django.contrib import messages

User = get_user_model()

from core.sock_connection import sock

from .models import Message
from .forms import MessageForm


class MessageList(generic.ListView):
    model = Message
    paginate_by = 20

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        dispatcher = super(MessageList, self).dispatch(request, *args,
                                                       **kwargs)
        if request.user.is_temp:
            raise Http404

        return dispatcher

    def get_queryset(self):
        queryset = super(MessageList, self).get_queryset()

        filter = self.kwargs.get('filter', None)

        if filter == 'all':
            queryset = queryset.filter(Q(recipient=self.request.user) | Q(sender=self.request.user))

        elif filter == 'outbox':
            queryset = queryset.filter(sender=self.request.user)

        else:
            queryset = queryset.filter(recipient=self.request.user)

        self.change_to_read(queryset)

        return queryset

    def change_to_read(self, queryset):
        not_updated = queryset.filter(recipient=self.request.user, is_read=False)

        if not_updated:
            not_updated.update(is_read=True)


class MessageCreate(generic.CreateView):
    model = Message
    form_class = MessageForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        dispatcher = super(MessageCreate, self).dispatch(request, *args,
                                                         **kwargs)
        return dispatcher

    def get_form_kwargs(self):
        kwargs = super(MessageCreate, self).get_form_kwargs()
        if self.kwargs.get('username'):
            kwargs['initial'].update({
                'recipient': self.kwargs.get('username')
            })

        return kwargs

    def form_valid(self, form):
        if self.request.user == form.cleaned_data.get('recipient'):
            messages.error(self.request, 'И кому это ты собрался сообщение написать?')
            return redirect(reverse("pm:new"))

        message = form.save(commit=False)
        message.sender = self.request.user
        message.save()

        messages.success(self.request, 'Сообщение отправлено.')

        # notify recipient about new message
        sock.send(
            sock.Action.NEW_PM,
            {
                "recipient": message.recipient.username
            }
        )

        return redirect(reverse("pm:inbox"))


@login_required
def delete_messages(request):
    rp = request.POST
    if request.user.is_temp or not rp:
        raise Http404

    list_to_delete = rp.get('delete_messages', None)
    if delete_messages:
        Message.objects.filter(id__in=list_to_delete).delete()

    return redirect('pm:inbox')

pm/templates/pm/message_form.html
{% extends 'base.html' %}

{% block title %}Новое сообщение |{% endblock %}

{% block content %}
    <!-- Begin p-navbar -->
    <div class="p-navbar">
        <a class="p-navbar_back" href="/">
            <i class="mic-arrow-back"></i>
        </a>
        <ul class="p-navbar_t">
            <li class="p-navbar_t_i">
                <h4>Новое сообщение</h4>
            </li>
        </ul>
    </div>
    <!-- End p-navbar -->

    <!-- Begin cnt -->
    <div class="cnt __hs __center __bg __padding">
        <form class="p-form" action="{{ request.get_full_path }}"
              enctype="multipart/form-data"
              method="post">
            {% include 'include/form.html' %}

            <button class="btn __raised __colored shadow-1 fr">Отправить</button>
            <a class="btn fr" href="{% url 'pm:inbox' %}">отмена</a>

            <div class="clearfix"></div>
        </form>
    </div>
    <!-- End cnt -->
{% endblock %}

pm/templates/pm/message_list.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}Входящие сообщения |{% endblock %}

{% block content %}

    <!-- Begin p-navbar -->
    <div class="p-navbar">
        <a class="p-navbar_back" href="{% url "chat:chat" %}">
            <i class="mic-arrow-back"></i>
        </a>
        <ul class="p-navbar_t">
            <li class="p-navbar_t_i">
                <h4>Входящие сообщения</h4>
            </li>
        </ul>

    </div>
    <!-- End p-navbar -->

    <div class="pm cnt __bg __sm">
        {% include "pm/include/_tabs.html" %}

        <a href="{% url 'pm:new' %}"
           class="pm_btn-new
                  btn __raised __colored __floated shadow-1 fr">
            <i class="btn_ic mic-add"></i>
        </a>

        <form action="{% url 'pm:delete' %}" method="POST">{% csrf_token %}
            <div class="pm_messages">

                {% for message in object_list %}
                    <!-- Begin pm_messages_i -->
                    <div class="pm_messages_i_cnt"
                         title="Кликните, чтобы отметить">
                        <input type="checkbox" id="msgCheck{{ message.id }}"
                               class="pm_messages_i_cnt_ich"
                               name="delete_messages"
                               value="{{ message.id }}"/>

                        <label class="pm_messages_i" for="msgCheck{{ message.id }}">

                            <div class="pm_messages_i_head">
                                <a href="{% url 'users:detail' message.sender %}"
                                   class="pm_messages_i_head_i">{{ message.sender }}</a>
                                <a href="{% url 'users:detail' message.recipient %}"
                                   class="pm_messages_i_head_i">{{ message.recipient }}</a>
                            </div>

                            <h4 class="pm_messages_i_t">
                                {{ message.subject }}
                            </h4>

                            <p class="pm_messages_i_text">{{ message.text }}</p>

                            <p class="pm_messages_i_date">{{ message.created }}</p>
                            {% if message.sender != request.user %}
                                <button
                                        onclick="nav.go('{% url 'pm:new_to' message.sender.username %}', false, true);event.preventDefault();"
                                        class="pm_messages_i_a-reply">Ответить
                                </button>
                            {% endif %}
                        </label>
                    </div>
                    <!-- End pm_messages_i -->
                    {% empty %}
                    <h3 class="pm_messages_msg">Пока нет сообщений</h3>
                {% endfor %}

            </div>
            {% if object_list %}
                <div class="pm_action">
                    <button class="btn" id="select_all_msg"
                            onclick="selectAll(this); event.preventDefault()">Выделить все
                    </button>
                    <button type="submit" class="btn __colored __raised">Удалить выделенные</button>
                </div>
            {% endif %}
        </form>

        <div class="pm_f">
            {% include 'core/paginator.html' %}
        </div>
    </div>

{% endblock %}

{% block vanilla %}
    <script type="text/javascript">
        function selectAll(el) {
            var inputs = geByClass('pm_messages_i_cnt_ich');

            if (!hasClass(el, '__selected')) {
                each(inputs, function (i, ich) {
                    ich.setAttribute('checked', 'checked');
                });
                addClass(el, '__selected');
            } else {
                each(inputs, function (i, ich) {
                    ich.removeAttribute('checked');
                });
                removeClass(el, '__selected');
            }
        }
    </script>
{% endblock %}

{% block js_footer %}
{% endblock %}