password/urls.py
from django.conf.urls import patterns, url
from password.views import ChangePassword, ResetFormView, ResetCompleteView,\
    ResetDone, ResetConfirm


urlpatterns = patterns(
    '',
    url(r'^change$', ChangePassword.as_view(), name='change'),
    url(r'^reset$', ResetFormView.as_view(), name='reset'),
    url(r'^reset/complete$', ResetCompleteView.as_view(), name='complete'),
    url(r'^reset/done$', ResetDone.as_view(), name='done'),
    url(r'^reset/(?P<pk>\d+)/(?P<code>\w+)$', ResetConfirm.as_view(),
        name='confirm'),
)

pm/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('pm.views',
                       url(r'^$', views.MessageList.as_view(), name='inbox'),
                       url(r'^/outbox$', views.MessageList.as_view(),
                           {'filter': 'outbox'}, name='outbox',
                           ),
                       url(r'^/all$', views.MessageList.as_view(),
                           {'filter': 'all'}, name='all', ),

                       url(r'^/new$', views.MessageCreate.as_view(), name='new', ),

                       url(r'^/new/(?P<username>\w+)$', views.MessageCreate.as_view(), name='new_to', ),

                       url(r'^/delete', 'delete_messages', name='delete',
                           ),
                       )

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^', include('core.urls', namespace='core')),
                       url(r'^', include('authn.urls', namespace='authn')),
                       url(r'^users/', include('users.urls', namespace='users')),
                       url(r'^pass/', include('password.urls', namespace='password')),
                       url(r'^reg/', include('registration.urls', namespace='registration')),

                       url(r'^', include('chat.urls', namespace='chat')),

                       url(r'^pm', include('pm.urls', namespace='pm')),
                       )

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}))

users/urls.py
# coding=utf-8
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from users.views import ProfileUpdate, ProfileDetail

urlpatterns = patterns('',
                       url(r'^(?P<username>\w+)/edit$', ProfileUpdate.as_view(), name='update'),
                       url(r'^(?P<username>\w+)$', ProfileDetail.as_view(), name='detail'),
                       )

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import auth
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.urlresolvers import reverse
from django.db import models
from django.http.response import Http404
from django.utils import timezone
from django.utils.text import capfirst
from sorl.thumbnail import ImageField, get_thumbnail
from sanitizer.models import SanitizedTextField, SanitizedCharField

from core.utils import path_and_rename, get_object_or_none


class UserManager(BaseUserManager):
    def create_user(self, password=None, username=None, **kwargs):
        user = self.model(
            is_active=False,
            **kwargs
        )
        if password:
            user.set_password(password)

        user.save(using=self._db)

        if not username:
            username = "guest%s" % user.id

        if get_object_or_none(User, username=username):
            raise Http404

        user.username = username
        user.save(update_fields=['username'])

        return user

    def create_superuser(self, password, username, **kwargs):
        superuser = self.create_user(
            password=password,
            username=username,
            is_staff=True,
            is_superuser=True,
            **kwargs
        )
        superuser.is_active = True
        superuser.save()
        return superuser


class User(AbstractBaseUser, PermissionsMixin):
    username = SanitizedCharField('Логин', max_length=30,
                                  unique=True, db_index=True,
                                  null=True)

    email = models.EmailField('email', unique=True, null=True,
                              help_text='Пример: ivanov@mail.ru')

    # personal
    first_name = models.CharField('имя', max_length=64, default='',
                                  blank=True, null=True)

    avatar = ImageField('аватар', upload_to=path_and_rename('avatars/'),
                        null=True, blank=True)

    about = SanitizedTextField(allowed_tags=['a', 'img'],
                               allowed_attributes=['href', 'src', 'width'],
                               strip=False, null=True, blank=True)

    is_temp = models.BooleanField('временный пользователь', default=False)

    # system
    is_active = models.BooleanField('активный', default=False)
    is_staff = models.BooleanField('персонал', default=False)
    activation_code = models.CharField('код подтверждения', max_length=32,
                                       null=True)
    reset_code = models.CharField('код подтверждения', max_length=32,
                                  null=True)
    date_joined = models.DateTimeField('дата регистрации',
                                       default=timezone.now)
    changed = models.DateTimeField('изменен', default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'username'

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'.encode('utf-8')
        ordering = ['-is_active', 'is_temp', 'date_joined']
        permissions = (
            ('view_user', 'Can view user profile'),
        )

    def __unicode__(self):
        return self.username

    @models.permalink
    def get_absolute_url(self):
        return 'users:detail', [self.pk]

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.first_name = capfirst(self.first_name.lower())
        super(User, self).save(force_insert, force_update, using,
                               update_fields)

    def get_admin_url(self):
        return reverse('admin:users_user_change', args=[self.id])

    def get_full_name(self):
        if self.first_name:
            return self.first_name
        return self.username

    get_full_name.short_description = 'полное имя'

    def get_short_name(self):
        if self.first_name:
            return self.first_name
        return self.username

    get_short_name.short_description = 'короткое имя'

    def get_activation_link(self):
        return reverse('registration:confirm',
                       args=(self.pk, self.activation_code))

    def get_avatar_40(self):
        if self.avatar:
            return get_thumbnail(self.avatar, '40x40', crop='center',
                                 format="PNG", quality=75).url
        else:
            return '/static/img/default/no_avatar.png'

    def get_short_about(self):
        if self.about:
            return self.about[:60]
        return None


class Group(auth.models.Group):
    class Meta:
        proxy = True
        verbose_name = 'группа пользователей'
        verbose_name_plural = 'группы пользователей'.encode('utf-8')

users/forms.py
# coding=utf-8
from __future__ import unicode_literals

import re

from django.core.exceptions import ValidationError
from django import forms

from .models import User


class ProfileForm(forms.ModelForm):
    about = forms.CharField(label='О себе', widget=forms.Textarea())

    username = forms.CharField(label='Ваш ник')
    avatar = forms.ImageField(label='Фото', required=False)

    class Meta:
        model = User
        fields = ('username', 'about', 'avatar')

    def clean_username(self):
        username = self.cleaned_data['username']
        users = User.objects.all()

        if re.search('^[a-z0-9_]+$', username):

            if username not in users.values_list('username', flat=True):

                if not re.match('^guest[\d]+$', username):
                    return username

                raise ValidationError('Такой ник только для гостей.')

            raise ValidationError('Этот ник уже занят.')

        raise ValidationError('Можно использовать только латинские символы, цифры и знак "_"')


class ProfileAdminForm(forms.ModelForm):
    password1 = forms.CharField(label='Пароль', required=False,
                                widget=forms.PasswordInput(
                                    attrs={'autocomplete': 'off'}))
    password2 = forms.CharField(label='Повторите пароль', required=False,
                                widget=forms.PasswordInput(
                                    attrs={'autocomplete': 'off'}))

    class Meta:
        model = User
        exclude = ('reset_code', 'activation_code')

    def clean_password2(self):
        cleaned_data = self.cleaned_data
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 or password2:
            if not password1 == password2:
                raise forms.ValidationError('Введенные пароли не совпадают.')

    def clean_photo(self):
        photo = self.cleaned_data.get('photo')

        try:
            if photo and photo._size > 2 * 1024 * 1024:
                raise ValidationError("Фото должно быть не больше 2мб")
            return photo
        except AttributeError:
            pass

users/views.py
# coding=utf-8
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import redirect, get_object_or_404
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic

from users.forms import ProfileForm
from users.models import User


class ProfileUpdate(generic.UpdateView):
    model = User
    form_class = ProfileForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        dispatcher = super(ProfileUpdate, self).dispatch(request, *args,
                                                         **kwargs)
        if request.user != self.object or request.user.is_temp:
            raise Http404

        return dispatcher

    def get_object(self, queryset=None):
        return get_object_or_404(User, username=self.kwargs.get('username', None))

    def form_valid(self, form):
        user = form.save(commit=False)
        user.changed = timezone.now()
        user.save()

        return redirect(reverse("chat:chat"))


class ProfileDetail(generic.DetailView):
    model = User

    def dispatch(self, request, *args, **kwargs):
        dispatcher = super(ProfileDetail, self).dispatch(request, *args,
                                                         **kwargs)
        if request.user.is_temp:
            raise Http404

        return dispatcher

    def get_object(self, queryset=None):
        return get_object_or_404(User, username=self.kwargs.get('username', None))

users/templates/users/user_detail.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}Профиль пользователя {{ object.get_full_name }} |{% endblock %}

{% block content %}

    <!-- Begin p-navbar -->
    <div class="p-navbar">
        <a class="p-navbar_back" href="{% url "chat:chat" %}">
            <i class="mic-arrow-back"></i>
        </a>
        <ul class="p-navbar_t">
            <li class="p-navbar_t_i">
                <h4>Профиль пользователя <b>{{ object.get_full_name }}</b></h4>
            </li>
        </ul>
        <ul class="p-navbar_r">
            <li class="p-navbar_r_i">
                <a href="{% url "users:update" request.user.username %}"
                   title="Изменить профиль"
                   class="p-navbar_r_i_a"
                        ><i class="mic-edit"></i></a>
            </li>
        </ul>
    </div>
    <!-- End p-navbar -->

    <!-- Begin mgr -->
    <div class="mgr cnt __bg __xhs">
        {% thumbnail user.avatar "440x440" crop="center" as im %}
            <img class="mgr_photo" src="{{ im.url }}"/>
            {% empty %}
            <img src="{{ STATIC_URL }}img/default/no_avatar.png"
                 class="mgr_photo">
        {% endthumbnail %}

        <h3 class="mgr_t">{{ user.manager.user.get_full_name }}</h3>

        <div class="mgr_b">
            <div class="mgr_b_l">
                <ul class="mgr_b_l_contacts">
                    {% if object.first_name %}
                        <li class="mgr_b_l_contacts_i" title="Имя">
                            Имя: {{ object.first_name }}
                        </li>
                    {% endif %}

                    <li class="mgr_b_l_contacts_i" title="Дата регистрации">
                        Дата регистрации: {{ object.date_joined }}
                    </li>

                    <li class="mgr_b_l_contacts_i" title="Последний визит">
                        Последний визит: {{ object.last_login }}
                    </li>
                </ul>
            </div>
            <div class="mgr_b_r">
                <div class="mgr_b_r_head">
                    Обо мне
                </div>
                <div class="mgr_b_r_about">
                    {{ object.about }}
                </div>
            </div>
        </div>
        <div class="mgr_f">
            {% if user != request.user %}
                <a href="{% url 'pm:new_to' user.username %}" class="btn __colored __raised">Отправить личное сообщение</a>
            {% endif %}
        </div>
    </div>
    <!-- End mgr -->

{% endblock %}

{% block vanilla %}
{% endblock %}

{% block js_footer %}
{% endblock %}

users/templates/users/user_form.html
{% extends 'base.html' %}

{% block title %}Мой профиль |{% endblock %}

{% block content %}

    <!-- Begin p-navbar -->
    <div class="p-navbar">
        <a class="p-navbar_back" href="{% url "chat:chat" %}">
            <i class="mic-arrow-back"></i>
        </a>
        <ul class="p-navbar_t">
            <li class="p-navbar_t_i">
                <h4>Мой профиль</h4>
            </li>
        </ul>
        <ul class="p-navbar_r">
            <li class="p-navbar_r_i">
                <a href="{% url "password:change" %}"
                   title="Просмотреть профиль"
                   class="p-navbar_r_i_a">
                    <i class="mic-lock"></i></a>
            </li>
            <li class="p-navbar_r_i">
                <a href="{% url "users:detail" request.user.username %}"
                   title="Сменить пароль"
                   class="p-navbar_r_i_a"
                        ><i class="mic-person"></i></a>
            </li>
        </ul>
    </div>
    <!-- End p-navbar -->

    <!-- Begin cnt -->
    <div class="cnt __bg __hs __padding">

        <form class="p-form" method="post" enctype="multipart/form-data">
            {% include 'include/form.html' %}

            <button class="btn __raised __colored shadow-1 fr">Сохранить</button>
            <button class="btn fr">Отмена</button>
            <div class="clearfix"></div>
        </form>

    </div>
    <!-- End cnt -->

{% endblock %}

{% block vanilla %}
{% endblock %}

{% block js_footer %}
{% endblock %}