authn/urls.py
# coding=utf-8
from __future__ import unicode_literals
from django.conf.urls import patterns, url
from authn.views import LoginView, LogoutView


urlpatterns = patterns('',
                       url(r'login$', LoginView.as_view(), name='login'),
                       url(r'logout$', LogoutView.as_view(), name='logout'),
                       )

password/urls.py
from django.conf.urls import patterns, url
from password.views import ChangePassword, ResetFormView, ResetCompleteView,\
    ResetDone, ResetConfirm


urlpatterns = patterns(
    '',
    url(r'^change$', ChangePassword.as_view(), name='change'),
    url(r'^reset$', ResetFormView.as_view(), name='reset'),
    url(r'^reset/complete$', ResetCompleteView.as_view(), name='complete'),
    url(r'^reset/done$', ResetDone.as_view(), name='done'),
    url(r'^reset/(?P<pk>\d+)/(?P<code>\w+)$', ResetConfirm.as_view(),
        name='confirm'),
)

pm/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('pm.views',
                       url(r'^$', views.MessageList.as_view(), name='inbox'),
                       url(r'^/outbox$', views.MessageList.as_view(),
                           {'filter': 'outbox'}, name='outbox',
                           ),
                       url(r'^/all$', views.MessageList.as_view(),
                           {'filter': 'all'}, name='all', ),

                       url(r'^/new$', views.MessageCreate.as_view(), name='new', ),

                       url(r'^/new/(?P<username>\w+)$', views.MessageCreate.as_view(), name='new_to', ),

                       url(r'^/delete', 'delete_messages', name='delete',
                           ),
                       )

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^', include('core.urls', namespace='core')),
                       url(r'^', include('authn.urls', namespace='authn')),
                       url(r'^users/', include('users.urls', namespace='users')),
                       url(r'^pass/', include('password.urls', namespace='password')),
                       url(r'^reg/', include('registration.urls', namespace='registration')),

                       url(r'^', include('chat.urls', namespace='chat')),

                       url(r'^pm', include('pm.urls', namespace='pm')),
                       )

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}))

registration/urls.py
# coding=utf-8
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from registration.forms import RegistrationForm
from registration.views import (RegistrationFormView,
                                RegistrationCompleteView,
                                RegistrationConfirmView)


urlpatterns = patterns(
    '',

    url(r'^basic$',
        RegistrationFormView.as_view(form_class=RegistrationForm),
        name='basic'),

    url(r'^welcome$',
        RegistrationCompleteView.as_view(),
        name='complete'),

    url(r'^confirm/(?P<pk>\d+)/(?P<code>\w+)$',
        RegistrationConfirmView.as_view(),
        name='confirm'),
)

authn/forms.py
# coding=utf-8
from __future__ import unicode_literals
from django import forms
from django.contrib.auth import authenticate, login
from django.utils.safestring import mark_safe
from authn.utils import send_activation_url_mail


DEACTIVATED = 'Ваш аккаунт отключен,<br>' \
              '<a href="/Contacts/">обратитесь к администратору.</a>'

INACTIVE = 'Этот аккаунт не был активирован. Мы повторно послали Вам письмо' \
           ' с инструкцией по активации. Проверьте свой email.'


class LoginForm(forms.Form):
    username = forms.CharField(label='Логин', help_text='Пример: fedorpidor')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput())

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        data = self.cleaned_data
        username = data.get('username', '').strip()
        password = data.get('password', '').strip()
        if password and username:
            user = authenticate(username=username, password=password)

            if not user:
                raise forms.ValidationError('Неправильное имя пользователя'
                                            ' или пароль.')
            if not user.is_active:
                if not user.activation_code:
                    # user deactivated by manager
                    raise forms.ValidationError(mark_safe(DEACTIVATED))
                else:
                    # resend activation link
                    send_activation_url_mail(user)
                    raise forms.ValidationError(mark_safe(INACTIVE))

            login(self.request, user)
        return data

authn/views.py
# coding=utf-8
from __future__ import unicode_literals
from urlparse import urlparse, urlunparse, urlsplit, urlunsplit
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.views import generic
from authn.forms import LoginForm


class LoginView(generic.FormView):
    form_class = LoginForm
    template_name = 'authn/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated() and not request.user.is_temp:
            return redirect('chat:chat')
        self.next = request.GET.get('next', '')
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        redirect_url = self.request.POST.get('next')
        parts = urlsplit(redirect_url)
        new_next = '', '', parts.path, parts.query, parts.fragment
        # return redirect(urlunsplit(new_next) or self.request.user)
        return redirect(urlunsplit(new_next) or 'chat:chat')

    def get_form_kwargs(self):
        kwargs = super(LoginView, self).get_form_kwargs()
        kwargs.update(request=self.request)
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context.update(next=self.next)
        return context


class LogoutView(generic.TemplateView):
    template_name = 'authn/logout.html'

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).dispatch(request, *args, **kwargs)

authn/templates/authn/base.html
{% extends 'base.html' %}

authn/templates/authn/login.html
{% extends 'authn/base.html' %}

{% block content %}

    <!-- Begin p-navbar -->
    <div class="p-navbar">
        <a class="p-navbar_back" href="/">
            <i class="mic-arrow-back"></i>
        </a>
        <ul class="p-navbar_t">
            <li class="p-navbar_t_i">
                <h4>Автоизация</h4>
            </li>
        </ul>
    </div>
    <!-- End p-navbar -->

    <!-- Begin cnt -->
    <div class="cnt __hs __center">

        <div class="__bg __padding">
            <p>
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% endif %}
            </p>

            <form class="p-form" action="{{ request.get_full_path }}" method="post">
                {% include 'include/form.html' %}

                <button class="btn __raised __colored shadow-1 fr">Войти</button>
                <a class="btn fr" href="{% url 'password:reset' %}">Напомнить пароль</a>

                <div class="clearfix"></div>
            </form>
            <div class="clearfix"></div>
        </div>

        <a style="padding-top: 24px;display: block;" href="{% url 'registration:basic' %}">Создать аккаунт</a>
    </div>
    <!-- End cnt -->

{% endblock %}

authn/templates/authn/logout.html
{% extends 'authn/base.html' %}

{% block content %}

    <!-- Begin p-navbar -->
    <div class="p-navbar">
        <a class="p-navbar_back" href="/">
            <i class="mic-arrow-back"></i>
        </a>
        <ul class="p-navbar_t">
            <li class="p-navbar_t_i">
                <h4>Сеанс завершен</h4>
            </li>
        </ul>
    </div>
    <!-- End p-navbar -->

    <div class="cnt __bg __hs __padding">

        Вы завершили сеанс работы с личным кабинетом на данном компьютере. Для
        повторного входа <a href="{% url 'authn:login' %}">воспользуйтесь
        формой</a> аутентификации.
    </div>

{% endblock %}